# Generated by Django 4.2.26 on 2025-12-01 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.aimodel'),
        ),
        migrations.AddField(
            model_name='airesponse',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.aiprovider'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai.aiprovider'),
        ),
        migrations.AddIndex(
            model_name='airesponse',
            index=models.Index(fields=['prompt_hash'], name='ai_airespon_prompt__7841b7_idx'),
        ),
    ]
