# Generated by Django 4.2.26 on 2025-12-01 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prd',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prd',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prds', to='github.repository'),
        ),
        migrations.AlterUniqueTogether(
            name='prd',
            unique_together={('title', 'version')},
        ),
    ]
